import os, sys, subprocess

Desktop = 'B:/Users/Shaun/Desktop/'
silentMiss = 'y'
FTPServer = 'y'
forensicsPath1 = 'B:/Users/Shaun/Desktop/Question1.txt'
forensicsAnswer1 = 'gb)'
checkForensicsQuestion1Value = '5'
disableGuest = 'y'
disableGuestValue = '5'
disableAdministrator = 'y'
disableAdministratorValue = '7'
requireCTRL_ALT_DEL = 'y'
requireCTRL_ALT_DELValue = '7'
checkFirewall = 'y'
checkFirewallValue = '7'
minPassAge = 'y'
minPassAgeValue = '7'
maxPassAge = 'y'
maxPassAgeValue = '7'
maxLoginTries = 'y'
maxLoginTriesValue = '7'
checkPassHist = 'y'
checkPassHistValue = '7'
checkPassCompx = 'y'
checkPassCompxValue = '7'
updateAutoInstall = 'y'
updateAutoInstallValue = '6'
